# rosservice call /search_Entity_in_room '{"room":"Kitchen","category_filter":["TABLE","CHAIR"],"min_confidence_filter":0.0}'
string room
# use '*' fro all object
string[] category_filter
# user None for all
time last_update_filter
# use 0.0 for all 
float32 min_confidence_filter
---
robocup_msgs/EntityList entity_list